### ISSUE TITLE
Update Doc: Instructions for editor setup and auto linting.

### ISSUE THREAD

**Issue by imabp** [asyncapi/cli#198]
#### Reason/Context
Please try answering a few of those questions
- Why do we need this improvement?
Improves Developer Experience, by auto-linting before any commit is made.

- How will this change help?
Adds auto-linting before any commit is made locally. Developers need to focus on the code, not on linting.
Also removes, the occurrences of unnecessary future commits which just includes linting.

- What is the motivation? 
I had to face linting issues while opening a PR. This will fix a lot of issues, whenever someone commits, 

#### Description
Please try answering few of those questions
- What changes have to be introduced?
Setup Husky and configure pre-commit hooks

- Will this be a breaking change?
No.

- How could it be implemented/designed?
Using Husky Pre-commit hook

**Comment by derberg** [comment]
I'm not a big fan of doing things like this as it is kind of invasive for folks that are used to work with git in the way that they commit often. I used husky in one of project, only because of required bundle generation, that I was always forgetting on a PR level and releasing without it. And it was always annoying me 😆 

I personally do not have problems with running linter as I have my VSC configured in a way that it is just automatically applying eslint rules (autofix) when I save changes in a file. Maybe this would be better, and should just be documented?

I wonder what other codeowners think 🤔 maybe there are other ways, like editorconfig?
@Souvikns @magicmatatjahu @boyney123

**Comment by imabp** [comment]
Yes, we can work out whatever works for now 😅
May be documenting whats required, will also  help :)

**Comment by boyney123** [comment]
Hey,

Yeah an interesting one really, I've been on projects with both limiting with husky and also post-commit linting (With CI etc), I think what I have learned is it comes down to preference really, some like one over the other, I can see why both are useful...

I have VSCode setup like @derberg which will lint and fix things on save for each project, so I never really run into these issues, so maybe we can add some docs to the README about Liniting help and guide people to setup VSCode to do that?

Good news is we have liniting checks in the CI so we have the value there.

@Souvikns @magicmatatjahu thoughts? I would be happy adding docs to help people setup editors (assuming that is VSCode...

**Comment by Souvikns** [comment]
As we have linting checks in CI I don't think we need anything else, but we could add docs to help people setup linting in their editors ( 😄  would help me as my vs code is not configured for linting and I manually do `npm run lint:fix` ).

**Comment by imabp** [comment]
I guess, its good to go with updating read me with necessary changes :)
🚀 

PS: _Changed the title_ 
@Souvikns @boyney123
