### ISSUE TITLE
Cannot convert AsyncAPI document

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/cli#329]
#### Describe the bug
While trying to use `asyncapi convert ...` I get a successful message and an error.

#### How to Reproduce
Given the following file:

```
{
    "asyncapi": "2.2.0",
    "info": {
        "title": "Rust server",
        "description": "test",
        "version": "0.8.0",
        "license": {
            "name": "Apache 2.0",
            "url": "https://www.apache.org/licenses/LICENSE-2.0.html"
        }
    },
    "servers": {
        "production": {
            "url": "148.251.43.103:4222",
            "protocol": "nats",
            "description": "GamingAPI NATS production broker"
        }
    },
    "defaultContentType": "json",
    "channels": {
        "v0/rust/servers/events/started": {
            "description": "Channel for the API to process for when a server has started",
            "subscribe": {
                "operationId": "ServerStarted",
                "description": "The Rust server can publish to this channel when the server has started",
                "message": {
                    "payload": {
                        "type": "string"
                    }
                }
            }
        }
    }
}
```

With the following command `asyncapi convert ./documents/test.json -o ./documents/output.json` 

I get the following output:

```
File ./documents/test.json successfully converted!
TypeError: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received an instance of Object
``

#### Expected behavior
Expected the file to be converted.

**Comment by derberg** [comment]
It might be related to the change in the API of the converter. The result of the conversion is not string and this is why writing to `output` maybe fails. @peter-rr do you have time to have a look? we are also missing a test of conversion with `--output flag.

**Comment by derberg** [comment]
@peter-rr hey, any chance you could have a look?

**Comment by peter-rr** [comment]
@derberg Sure! Let me check it 👀

**Comment by peter-rr** [comment]
I've been testing with different files and formats and it seems the error is only happening with `.json` files. The [writeFile() function](https://github.com/peter-rr/cli/blob/6c52cf4ef950789eedb59119dd57c31ea2221342/src/commands/convert.ts#L50) does not accept an instance of Object as an argument, so that the converted file is not saved as an output file.

When `--output` flag is not passed, we can see the file is actually converted except for the "subscribe" object as you can see in the following log:

![image](https://user-images.githubusercontent.com/81691177/230679935-6afd2500-2363-4019-b4b4-039659366c66.png)

I've come up with a [quick fix](https://github.com/asyncapi/cli/pull/509) which seems to solve the issue. The output is not properly formatted, though 🤔

![image](https://user-images.githubusercontent.com/81691177/230681335-5f3c722c-eab5-404d-8676-e844c32d64d7.png)



 Let me know what you think :) Also I need to add a test of conversion for `--output` flag.

**Comment by derberg** [comment]
cool! left a comment
