### ISSUE TITLE
Validation of default files in CWD does not work when I have no files in the context

### ISSUE THREAD

**Issue by derberg** [asyncapi/cli#35]
This is how you can reproduce it:
```
$ asyncapi context list
myapp1 : /Users/wookiee/sources/cli/test/spec.yaml
$ asyncapi context current
No context is set as current, please set a current context.
$ asyncapi validate
File: /Users/wookiee/sources/cli/asyncapi.yaml successfully validated!
$ asyncapi context remove myapp1
context deleted successfully
$ asyncapi context list
No contexts saved yet.
$ asyncapi validate
No contexts saved yet, run asyncapi --help to know more.
```

in case I do `asyncapi validate` and, flags like `--context` or `--files` are not passed, and there is no default context + no contexts at all, the validation of default files from CWD should work

**Comment by Souvikns** [comment]
@derberg shall I start with this issue next ?

**Comment by derberg** [comment]
yeap

**Comment by Souvikns** [comment]
## Error 
When the global context file is absent, so no default context is present, and also when flags are missing but there is an `asyncapi.yml` file in the working directory, It should load that file automatically, but it is throwing `No contexts saved yet, run asyncapi --help to know more.` error. 

## Cause of Error 
This is happening because of https://github.com/asyncapi/cli/blob/b459c1c79f27253524def11576298e0aee45831d/src/hooks/context/hooks.tsx#L136 loading the context file before checking for auto-detection. It is needed because to read the `--context` flag we need the global context config. 

## Two Possible Solution 

1. If we give auto-detection first priority then in this scenario the CLI will auto-detect files first and not load the global config. But doing this will change the default behavior as it will not look for global current context first, but only if there is no `asyncapi.yml` file in the working directory. This could be beneficial in some scenarios. 

2. After we catch the `ContextFileNotFoundError` we check for the `asyncapi.yml` file in the working directory and throw an error if it is not found. This way the default behavior will not change but fix the issue with this scenario. 

> @derberg what do you think, which approach should I follow. 
---
 
https://github.com/asyncapi/cli/blob/b459c1c79f27253524def11576298e0aee45831d/src/hooks/context/hooks.tsx#L126-L162

**Comment by derberg** [comment]
I'm definitely with 2, just make sure message thrown to the user clearly explains cause and next steps
