### ISSUE TITLE
tests fail in Windows environment

### ISSUE THREAD

**Issue by KhudaDad414** [asyncapi/cli#416]
#### Describe the bug
For some reason, windows tests fail in PRs periodically(more like 70% of the time).
https://github.com/asyncapi/cli/actions/runs/3694401317/jobs/6256931933
https://github.com/asyncapi/cli/actions/runs/3656480521/jobs/6178974421
https://github.com/asyncapi/cli/actions/runs/3567406500/jobs/5995068352

I see it has been going on for some time now.

**Comment by jonaslagoni** [comment]
Having the same problem in https://github.com/asyncapi/cli/pull/374 now 🙂

**Comment by derberg** [comment]
I write the only reason I know in https://github.com/asyncapi/cli/pull/397#discussion_r1054388072

basically, best practice is to have each `test` under separate `describe` because of these cleanups, when files are removed, stuff like that. Windows is probably slow crap and sometimes when text operates on files, and "creates" one, the other version of it was not yet removes by the cleanup and then permissions issues show up.

not sure if this is the reason, but the fix always works

**Comment by jonaslagoni** [comment]
Just stopped the release workflow: https://github.com/asyncapi/cli/actions/runs/3928533695/jobs/6716261065

**Comment by derberg** [comment]
yeah, that is the story of the past, no longer issues in there
